// Helpers for the managed Node-RED app type.
//
// A Node-RED app is not built from a user repo — it runs the official
// `nodered/node-red` image with a persistent named volume mounted at the
// Node-RED user dir. Editor access is controlled by `adminAuth` in settings.js,
// which we generate from the app's NodeRedUser records (bcrypt password hash +
// permission level). Regenerating settings.js + restarting the container is how
// account changes take effect.

import * as bcryptjs from 'bcryptjs';

// Hash an editor password EXACTLY the way Node-RED does. Node-RED's adminAuth
// verifies with the pure-JS `bcryptjs` library, and its own `node-red-admin
// hash-pw` tool generates `$2a$` hashes at cost factor 8. We mirror that
// precisely — same library, same cost, `$2a$` prefix — so a hash we generate is
// byte-for-byte the kind Node-RED produces and always verifies. (The C++
// `bcrypt` lib's `$2b$` hashes mostly interoperate, but matching Node-RED's
// exact scheme removes any cross-implementation doubt.)
export const NODERED_BCRYPT_COST = 8;

export function hashNodeRedPassword(plain: string): string {
  const hash = bcryptjs.hashSync(plain, NODERED_BCRYPT_COST);
  // Normalize the version tag to `$2a$` (what node-red-admin emits). bcryptjs
  // and Node-RED both treat `$2a$`/`$2b$` as the same algorithm, but `$2a$` is
  // the canonical Node-RED form.
  return hash.replace(/^\$2[aby]\$/, '$2a$');
}

// Official Node-RED image. Pinned to a major tag for reproducibility; bump
// deliberately when validating a new Node-RED release.
export const NODERED_IMAGE = 'nodered/node-red:4.0';

// The Node-RED user dir inside the container (the official image's default).
// The persistent volume is mounted here so flows, installed nodes and the
// generated settings.js survive restarts/redeploys.
export const NODERED_DATA_DIR = '/data';

// The official nodered/node-red image runs as the non-root user "node-red"
// (uid:gid 1000:1000). The /data volume (and anything we drop into it from a
// root helper container) MUST be owned by this uid or Node-RED gets EACCES and
// fails to start (it can't create /data/node_modules, flows, etc.).
export const NODERED_UID = 1000;
export const NODERED_GID = 1000;

// Node-RED's editor/admin HTTP server listens on 1880 inside the container.
// Traefik routes the app's subdomain to this port over the Docker network; no
// host port is published (the URL stays clean with no :1880).
export const NODERED_PORT = 1880;

// Name the persistent data volume after the subdomain (mirrors the Frappe
// volume naming scheme: `zonal-frappe-<subdomain>`).
export function noderedVolumeName(subdomain: string): string {
  return `zonal-nodered-${subdomain}`;
}

export interface NodeRedUserSpec {
  username: string;
  passwordHash: string;
  // "*" = full access, "read" = read-only.
  permission: string;
}

// Render the settings.js dropped into the Node-RED data volume. It wires up
// adminAuth from the supplied users so the editor requires login. With no users
// configured, adminAuth is omitted (Node-RED then has an open editor) — the
// caller always seeds at least one admin, so that is a safety fallback only.
//
// Username/permission are validated/whitelisted by the caller; the bcrypt hash
// is `$2…`-safe. We still JSON.stringify every value so nothing can break out
// of the JS string literal.
export function renderNodeRedSettings(users: NodeRedUserSpec[]): string {
  const userObjects = users
    .map(
      (u) =>
        `        { username: ${JSON.stringify(u.username)}, ` +
        `password: ${JSON.stringify(u.passwordHash)}, ` +
        `permissions: ${JSON.stringify(u.permission === 'read' ? 'read' : '*')} }`,
    )
    .join(',\n');

  const adminAuth = users.length
    ? `
  adminAuth: {
    type: 'credentials',
    users: [
${userObjects}
    ],
  },`
    : '';

  // Generated by Zonal Cloud — do not edit by hand. Rewritten on every account
  // change (which also restarts the container). Honors the standard Node-RED
  // env vars the running container is started with.
  return `// Generated by Zonal Cloud — managed Node-RED settings. Do not edit by hand;
// changes are overwritten when editor accounts are updated.
module.exports = {
  flowFile: 'flows.json',
  uiPort: process.env.PORT || ${NODERED_PORT},
  // Bind to all interfaces — Node-RED defaults to 127.0.0.1, which would refuse
  // connections from the published host port and from Traefik on the network.
  uiHost: '0.0.0.0',
  userDir: '${NODERED_DATA_DIR}',${adminAuth}
  functionGlobalContext: {},
  exportGlobalContextKeys: false,
  logging: {
    console: {
      level: 'info',
      metrics: false,
      audit: false,
    },
  },
  editorTheme: {
    projects: { enabled: false },
  },
};
`;
}
